# Generated by Django 4.0.3 on 2023-06-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliov2', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('editedOn', models.DateTimeField(auto_now=True)),
                ('isVisible', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('imgSrc', models.ImageField(upload_to='portfoliov2/pictures/')),
            ],
        ),
    ]
