# Generated by Django 4.0.3 on 2023-06-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliov2', '0004_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Projects',
        ),
    ]
