# Generated by Django 4.0.3 on 2023-06-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliov2', '0005_rename_project_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('3D Modelling', '3D Modelling'), ('Music', 'Music'), ('Video', 'Video')], max_length=100),
        ),
    ]
