# Generated by Django 4.0.3 on 2023-06-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliov2', '0006_alter_projects_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='imgSrc',
            field=models.FileField(blank=True, upload_to='portfoliov2/static/portfoliov2/pictures/'),
        ),
    ]
