# Generated by Django 4.0.3 on 2023-06-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliov2', '0008_alter_projects_imgsrc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['category']},
        ),
    ]
