# Generated by Django 4.0.3 on 2023-06-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliov2', '0010_alter_projects_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.IntegerField(choices=[(1, 'Programming'), (2, '3D Modelling'), (3, 'Music'), (4, 'Video')]),
        ),
    ]
