# Generated by Django 4.0.3 on 2023-06-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliov2', '0012_alter_projects_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='imgSrc',
            field=models.FilePathField(blank=True, path='/static/portfoliov2/pictures/', recursive=True),
        ),
    ]
