# Generated by Django 4.0.3 on 2023-06-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliov2', '0013_alter_projects_imgsrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='imgSrc',
            field=models.FilePathField(blank=True, path='portfoliov2/static/portfoliov2/pictures/', recursive=True),
        ),
    ]
