# Generated by Django 4.0.3 on 2023-06-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliov2', '0015_alter_projects_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='projects',
            name='modelSrc',
            field=models.CharField(default='', max_length=100),
        ),
    ]
