# Generated by Django 4.0.3 on 2023-06-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliov2', '0016_projects_details_projects_modelsrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='categorySymbol',
            field=models.CharField(blank=True, choices=[('', 'Programming'), ('fa-solid fa-cube', '3D Modelling'), ('', 'Music'), ('', 'Video')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projects',
            name='modelSrc',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
