# Generated by Django 4.0.3 on 2023-06-23 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliov2', '0017_projects_categorysymbol_alter_projects_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='modelSrc',
        ),
        migrations.AlterField(
            model_name='projects',
            name='categorySymbol',
            field=models.CharField(blank=True, choices=[('fa-solid fa-code', 'Programming'), ('fa-solid fa-cube', '3D Modelling'), ('fa-solid fa-music', 'Music'), ('fa-solid fa-video', 'Video')], default='', max_length=100),
        ),
        migrations.CreateModel(
            name='ProjectModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelSrc', models.CharField(blank=True, default='', max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfoliov2.projects')),
            ],
        ),
    ]
