# Generated by Django 4.0.3 on 2023-06-23 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliov2', '0018_remove_projects_modelsrc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodels',
            name='project',
            field=models.ForeignKey(limit_choices_to={'category': '3D Modelling'}, on_delete=django.db.models.deletion.CASCADE, to='portfoliov2.projects'),
        ),
        migrations.CreateModel(
            name='ProjectMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicSrc', models.CharField(blank=True, default='', max_length=100)),
                ('interpreter', models.CharField(blank=True, default='', max_length=100)),
                ('genre', models.CharField(blank=True, default='', max_length=100)),
                ('project', models.ForeignKey(limit_choices_to={'category': 'Music'}, on_delete=django.db.models.deletion.CASCADE, to='portfoliov2.projects')),
            ],
        ),
    ]
