# Generated by Django 4.0.3 on 2023-06-25 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliov2', '0019_alter_projectmodels_project_projectmusic'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmusic',
            name='createdOn',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 25, 2, 34, 11, 666630)),
        ),
    ]
