# Generated by Django 4.0.3 on 2023-06-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliov2', '0021_article_remove_projectmusic_createdon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecodeexample',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articlepicture',
            name='article',
        ),
        migrations.RemoveField(
            model_name='projectprogramming',
            name='project',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ArticleCodeExample',
        ),
        migrations.DeleteModel(
            name='ArticlePicture',
        ),
        migrations.DeleteModel(
            name='ProjectProgramming',
        ),
    ]
