# Generated by Django 4.0.3 on 2023-06-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliov2', '0021_article_remove_projectmusic_createdon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='isVisible',
            field=models.BooleanField(default=True),
        ),
    ]
