# Generated by Django 4.0.3 on 2023-06-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliov2', '0023_article_projectprogramming_articlepicture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='project',
            new_name='projectProgramming',
        ),
    ]
