# Generated by Django 4.0.3 on 2023-06-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliov2', '0022_article_isvisible'),
        ('portfoliov2', '0024_rename_project_article_projectprogramming'),
    ]

    operations = [
    ]
