# Generated by Django 4.0.3 on 2023-09-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliov2', '0025_merge_20230630_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articlecodeexample',
            name='code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='articlecodeexample',
            name='language',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='articlepicture',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
