# Generated by Django 4.0.3 on 2023-09-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliov2', '0026_alter_article_content_alter_articlecodeexample_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='description_de',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projects',
            name='details_de',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projects',
            name='imgSrc',
            field=models.TextField(blank=True, default=''),
        ),
    ]
