# Generated by Django 4.0.3 on 2023-09-10 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliov2', '0027_rename_description_projects_description_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='details',
            new_name='details_en',
        ),
    ]
