# Generated by Django 4.0.3 on 2023-09-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliov2', '0028_rename_description_projects_description_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencestations',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='experiencestations',
            old_name='station',
            new_name='station_en',
        ),
        migrations.RenameField(
            model_name='experiencestations',
            old_name='title',
            new_name='title_en',
        ),
    ]
