# Generated by Django 4.0.3 on 2023-09-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliov2', '0030_experiencestations_description_de_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='projects',
            name='title_de',
            field=models.CharField(default='', max_length=100),
        ),
    ]
