# Generated by Django 4.0.3 on 2023-09-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliov2', '0032_rename_content_article_content_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_de',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='title_de',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
