# Generated by Django 4.0.3 on 2023-09-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliov2', '0033_article_content_de_article_title_de'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepicture',
            name='imgSrc',
            field=models.TextField(blank=True, default=''),
        ),
    ]
