# Generated by Django 4.0.3 on 2023-09-14 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliov2', '0035_articlecodeexample_downloadlink_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecodeexample',
            name='downloadLink',
        ),
        migrations.RemoveField(
            model_name='articlecodeexample',
            name='githubLink',
        ),
    ]
