# Generated by Django 4.0.3 on 2023-09-14 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliov2', '0036_remove_articlecodeexample_downloadlink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCodeLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloadLink', models.TextField(blank=True, default='')),
                ('githubLink', models.TextField(blank=True, default='')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfoliov2.article')),
            ],
        ),
    ]
